///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
// * All rights reserved.</center></h2>
// *
// * This software component is licensed by ST under BSD 3-Clause license,
// * the "License"; You may not use this file except in compliance with the
// * License. You may obtain a copy of the License at:
// *                        opensource.org/licenses/BSD-3-Clause
// *
// ******************************************************************************
// */



#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
//#include "core_cm3.h"
#include "Scheduler.h"

uint8_t TaskA_LED , TaskB_LED ,TaskC_LED;

Taskref TaskA , TaskB , TaskC;
void Task_A(void){
	while(1){
		TaskA_LED ^= 1;
	}
}

void Task_B(void){
	while(1){
		TaskB_LED ^= 1;
	}
}

void Task_C(void){
	while(1){
		TaskC_LED ^= 1;
	}
}


int main(void)
{
	RadwaRTOS_error error;
	HW_init();
	if (RadwaRTOS_Init() != no_error){
		while(1);
	}

	TaskA.stack_size = 1024;
	TaskA.Priority = 8;
	TaskA.task_entry = Task_A;
	strcpy(TaskA.Task_name , "Task_A");

	TaskB.stack_size = 1024;
	TaskB.Priority = 8;
	TaskB.task_entry = Task_B;
	strcpy(TaskB.Task_name , "Task_B");

	TaskC.stack_size = 1024;
	TaskC.Priority = 8;
	TaskC.task_entry = Task_C;
	strcpy(TaskC.Task_name , "Task_C");



	error += RadwaRTOS_CREATE_TASK(&TaskA);
	error += RadwaRTOS_CREATE_TASK(&TaskB);
	error += RadwaRTOS_CREATE_TASK(&TaskC);


	RadwaRTOS_ACTIVATE_TASK(&TaskA);
	RadwaRTOS_ACTIVATE_TASK(&TaskB);
	RadwaRTOS_ACTIVATE_TASK(&TaskC);


	RadwaRTOS_Activate_OS();
	while(1){

	}
	return 0;
}




