#make file by radwa mahmoud
CC=arm-none-eabi-
CFLAGS=-gdwarf-2 -mcpu=cortex-m3
INCS=-I .
LIBS=
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As=$(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name=learn-in-depth
all: $(project_name).hex
	@echo "everything done"
$(project_name).hex: $(project_name).elf
	$(CC)objcopy.exe -O binary $<  $@
$(project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=mapfile.map
%.o: %.c
	$(CC)gcc.exe $(CFLAGS) $(INCS) -c $< -o $@
%.o: %.s
	$(CC)As.exe $(CFLAGS) $< -o $@
clean:
	rm *.elf *.bin
clean_all:
	rm *.o *.elf *.bin *.hex
	@echo "everything is clean"