///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
// * All rights reserved.</center></h2>
// *
// * This software component is licensed by ST under BSD 3-Clause license,
// * the "License"; You may not use this file except in compliance with the
// * License. You may obtain a copy of the License at:
// *                        opensource.org/licenses/BSD-3-Clause
// *
// ******************************************************************************
// */



#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "core_cm3.h"



/*
 * =======================================================================================
 * 										MACROS
 * =======================================================================================
 */


#define SVC_ADD										0
#define SVC_SUB 									1
#define SVC_MUL										2




/*
 * =======================================================================================
 * 										FUNCTIONS
 * =======================================================================================
 */
void OS_SVC(uint32_t *Stack_frame){
	uint8_t first_val =Stack_frame[0] , second_val = Stack_frame[1] ;
	uint8_t SVC_number = *((uint8_t *)(((uint8_t *)Stack_frame[6]) -2));
	switch(SVC_number){
	case SVC_ADD:
		Stack_frame[0] = first_val + second_val;
		break;
	case SVC_SUB:
		Stack_frame[0] = first_val - second_val;
		break;
	case SVC_MUL:
		Stack_frame[0] = first_val * second_val;
		break;
	}
}

__attribute ((naked))void SVC_Handler (void)
{
	__asm volatile("tst lr ,#0x4 \n\t"
			"ITE EQ \n\t"
			"mrseq r0, MSP \n\t"
			"mrsne r0 , PSP \n\t"
			"B OS_SVC");
}


int OS_SVC_SET(int a, int b , int choice){

	int result;
	switch(choice){
	case SVC_ADD:
		__asm volatile("SVC #0x00");
		break;
	case SVC_SUB:
		__asm volatile("SVC #0x01");
		break;
	case SVC_MUL:
		__asm volatile("SVC #0x02");
		break;
	}



	__asm("mov %0 , r0"
			:"=r" (result));
	return result;
}


void clk_init(void);



void HardFault_Handler(){
}

int main(void)
{
	int result;
	result = OS_SVC_SET(5,3,SVC_ADD);
	result = OS_SVC_SET(5,3,SVC_SUB);
	result = OS_SVC_SET(5,3,SVC_MUL);

	while(1){

	}
	return 0;
}


void clk_init(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}
