#make file by radwa mahmoud
CC=arm-none-eabi-
CFLAGS=-mcpu=cortex-m4 -mthumb -gdwarf-2 -g
INCS=-I .
LIBS=
SRC=$(wildcard *.c)
OBJ=$(SRC:.c=.o)
As=$(wildcard *.s)
AsOBJ=$(As:.s=.o)
project_name=lesson3-lab3
all: $(project_name).bin
	@echo "everything done"
$(project_name).bin: $(project_name).elf
	$(CC)objcopy.exe -O binary $<  $@
$(project_name).elf: $(OBJ) $(AsOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(AsOBJ) -o $@ -Map=mapfile.map
	cp $(project_name).elf $(project_name).axf
%.o: %.c
	$(CC)gcc.exe $(CFLAGS) $(INCS) -c $< -o $@
%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@
clean:
	rm *.elf *.bin
clean_all:
	rm *.o *.elf *.bin
	@echo "everything is clean"