/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>
//portA
#define PORTA_BASE 	0x40010800
#define GPIOA_CRH		*(volatile uint32_t*)(PORTA_BASE + 0x04)
#define GPIOA_IDR		*((volatile uint32_t*)(PORTA_BASE + 0x08))
#define GPIOA_CRL		*(volatile uint32_t*)(PORTA_BASE + 0x00)
//portB
#define PORTB_BASE 0x40010C00
#define GPIOB_CRH		*(volatile uint32_t*)(PORTB_BASE + 0x04)
#define GPIOB_ODR		*((volatile uint32_t*)(PORTB_BASE + 0x0c))
#define GPIOB_CRL		*(volatile uint32_t*)(PORTB_BASE + 0x00)

//rcc
#define RCC_Base 	0x40021000
#define RCC_APB2ENR *((volatile uint32_t*)( RCC_Base +0x18))
//#define RCC_CFGR 	*((volatile uint32_t*)( RCC_Base + 0x04))
//#define RCC_CR		*((volatile uint32_t*)( RCC_Base + 0x0))


void clk_init(void){

	RCC_APB2ENR |= 1<<2; //gpio A enable
	RCC_APB2ENR |= 1<<3; //gpio B enable
}
void gpio_init(void){

//gpio A : pin 13 , 1 as floating input
	GPIOA_CRH   &= 0xFF0FFFFF;
	GPIOA_CRH   |= 0x00400000;
	GPIOA_CRL   &= 0xFFFFFF0F;
	GPIOA_CRL   |= 0x00000040;

//gpio B : pin 13 , 1 as output push pull , 10 MHZ
	GPIOB_CRH   &= 0xFF0FFFFF;
	GPIOB_CRH   |= 0x00200000;
	GPIOB_CRL   &= 0xFFFFFF0F;
	GPIOB_CRL   |= 0x00000020;

}
int main(void)
{
	clk_init();
	gpio_init();
	volatile int i;

	while(1){
		if((GPIOA_IDR&(1<<1))>>1==0){
			GPIOB_ODR ^= (1<<1);
			while((GPIOA_IDR&(1<<1))>>1 ==0);
		}
		if((GPIOA_IDR&(1<<13))>>13 ==1){
			GPIOB_ODR ^= (1<<13);
		}
		for(i=0;i<3000;i++);
	}
	return 0;
}
