///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
// * All rights reserved.</center></h2>
// *
// * This software component is licensed by ST under BSD 3-Clause license,
// * the "License"; You may not use this file except in compliance with the
// * License. You may obtain a copy of the License at:
// *                        opensource.org/licenses/BSD-3-Clause
// *
// ******************************************************************************
// */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "LCD.h"
uint8_t flag =0;

#define Switch_CPU_Access_TO_PRIVILIGED			__asm volatile("mrs r0 , CONTROL \n\t" \
		"lsr r0,r0 , #1 \n\t" \
		"lsl r0,r0 , #1  \n\t" \
		"msr CONTROL , r0")



#define Switch_CPU_Access_TO_UNPRIVILIGED		__asm volatile("mrs r0 , CONTROL \n\t" \
		"orr r0,r0 , #0x01 \n\t" \
		"msr CONTROL , r0")







void _wait_ms(uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++)
			;
}


void EXTI9_CALLBACK(void){

	flag =1;
}

void clk_init(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}


void HardFault_Handler(){
	Switch_CPU_Access_TO_PRIVILIGED;
}

int main(void)
{
	clk_init();

	Switch_CPU_Access_TO_UNPRIVILIGED;

	EXTI_PinConfig_t pincfg;
	pincfg.EXTI_PIN = EXTI9PB9;
	pincfg.IRQ_EN = EXTI_IRQ_ENABLE;
	pincfg.Trigger_case = EXTI_TRIGGER_RISING;
	pincfg.P_IRQ_Callback =EXTI9_CALLBACK;

	MCAL_EXTI_GPIO_Init(&pincfg);




	flag=1;

	while(1){
		if(flag ){
			flag =0;
		}
	}
	return 0;
}



