///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
// * All rights reserved.</center></h2>
// *
// * This software component is licensed by ST under BSD 3-Clause license,
// * the "License"; You may not use this file except in compliance with the
// * License. You may obtain a copy of the License at:
// *                        opensource.org/licenses/BSD-3-Clause
// *
// ******************************************************************************
// */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "stm32f103x6.h"
#include "Stm32_F103C6_gpio_driver.h"



void clk_init(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void gpio_init(void){

	GPIO_PinConfig_t  pinConfig;
	//gpio A : pin 13 , 1 as floating input


	pinConfig.PinNo = PIN13;
	pinConfig.Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &pinConfig);

	pinConfig.PinNo = PIN1;
	pinConfig.Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, &pinConfig);

	//gpio B : pin 13 , 1 as output push pull , 10 MHZ


	pinConfig.PinNo = PIN13;
	pinConfig.Mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.speed =OUTPUT_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, &pinConfig);

	pinConfig.PinNo = PIN1;
	pinConfig.Mode = GPIO_MODE_OUTPUT_PP;
	pinConfig.speed =OUTPUT_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, &pinConfig);

}


int main(void)
{
	clk_init();
	gpio_init();
	volatile int i;

	while(1){
		if((MCAL_GPIO_READ_PIN(GPIOA,PIN1))==PIN_RESET){
			MCAL_GPIO_TOGGLE_PIN(GPIOB, PIN1);
			while((MCAL_GPIO_READ_PIN(GPIOA,PIN1))==0);
		}
		if((MCAL_GPIO_READ_PIN(GPIOA,PIN13)) ==PIN_SET){
			MCAL_GPIO_TOGGLE_PIN(GPIOB, PIN13);
		}
		for(i=0;i<3000;i++);
	}
	return 0;
}



