///**
// ******************************************************************************
// * @file           : main.c
// * @author         : Auto-generated by STM32CubeIDE
// * @brief          : Main program body
// ******************************************************************************
// * @attention
// *
// * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
// * All rights reserved.</center></h2>
// *
// * This software component is licensed by ST under BSD 3-Clause license,
// * the "License"; You may not use this file except in compliance with the
// * License. You may obtain a copy of the License at:
// *                        opensource.org/licenses/BSD-3-Clause
// *
// ******************************************************************************
// */



#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "LCD.h"

/*
 * =======================================================================================
 * 										GLOBAL VARIABLES
 * =======================================================================================
 */
uint8_t flag =0 , flag_A , flag_B;

extern _estack;

uint32_t S_MSP = &_estack;
uint32_t E_MSP, S_TASKA_PSP ,E_TASKA_PSP , S_TASKB_PSP , E_TASKB_PSP;


/*
 * =======================================================================================
 * 										MACROS
 * =======================================================================================
 */

#define Switch_CPU_Access_TO_PRIVILIGED			__asm volatile("mrs r0 , CONTROL \n\t" \
		"lsr r0,r0 , #1 \n\t" \
		"lsl r0,r0 , #1  \n\t" \
		"msr CONTROL , r0")



#define Switch_CPU_Access_TO_UNPRIVILIGED		__asm volatile("mrs r0 , CONTROL \n\t" \
		"orr r0,r0 , #0x01 \n\t" \
		"msr CONTROL , r0")


#define Switch_OS_TO_PSP		__asm volatile("mrs r0 , CONTROL \n\t" \
		"orr r0,r0 , #0x02 \n\t" \
		"msr CONTROL , r0")

#define Switch_OS_TO_MSP	__asm volatile("mrs r0 , CONTROL \n\t" \
		"and r0,r0 , #0x05 \n\t" \
		"msr CONTROL , r0")

#define SET_PSP(task_psp)	__asm volatile(" mov r0 ,%[in1] \n\t msr PSP , r0 " \
		: \
		  :[in1] "r" (task_psp))



#define OS_Generate_Interrupt   __asm("SVC #0x3")


#define  TaskA_Size			100
#define  TaskB_Size			100



/*
 * =======================================================================================
 * 										TASKS
 * =======================================================================================
 */

uint8_t TASKA(uint8_t a ,uint8_t b ,uint8_t c ){
	return a+b+c;
}


uint8_t TASKB(uint8_t a ,uint8_t b ,uint8_t c ,uint8_t d){
	return a+b+c+d;
}

/*
 * =======================================================================================
 * 										FUNCTIONS
 * =======================================================================================
 */


void SVC_Handler (void)
{
	Switch_CPU_Access_TO_PRIVILIGED;
}



void EXTI9_CALLBACK(void){

	if(flag ==0){
		flag_A =1;
		flag =1;
	}
	else if (flag ==1){
		flag_B =1;
		flag =0;
	}
}

void Main_OS(){

	//MSP
	E_MSP = S_MSP - 512;
	// task A
	S_TASKA_PSP =E_MSP -8 ;
	E_TASKA_PSP = S_TASKA_PSP -TaskA_Size;

	//task B

	S_TASKB_PSP =E_TASKA_PSP -8 ;
	E_TASKB_PSP = S_TASKB_PSP -TaskB_Size;


	while(1){

		if(flag_A  ==1){
			flag_A =0;
			SET_PSP(S_TASKA_PSP);
			Switch_OS_TO_PSP;
			Switch_CPU_Access_TO_UNPRIVILIGED;
			flag_A = TASKA(1,2,3);
			OS_Generate_Interrupt;
			Switch_OS_TO_MSP;

		}
		if(flag_B  ==1){
			flag_B =0;
			SET_PSP(S_TASKB_PSP);
			Switch_OS_TO_PSP;
			Switch_CPU_Access_TO_UNPRIVILIGED;
			flag_B = TASKB(1,2,3,4);
			OS_Generate_Interrupt;
			Switch_OS_TO_MSP;
		}
	}
}

void clk_init(void);



void HardFault_Handler(){
}

int main(void)
{
	clk_init();


	EXTI_PinConfig_t pincfg;
	pincfg.EXTI_PIN = EXTI9PB9;
	pincfg.IRQ_EN = EXTI_IRQ_ENABLE;
	pincfg.Trigger_case = EXTI_TRIGGER_RISING;
	pincfg.P_IRQ_Callback =EXTI9_CALLBACK;

	MCAL_EXTI_GPIO_Init(&pincfg);

	Main_OS();


	while(1){

	}
	return 0;
}


void clk_init(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}
