/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 *******************************************************************************/
#include <stdio.h>
#include <stdint.h>

#define RCC_BASE 	0x40021000
#define PORTA_BASE 	0x40010800
#define EXTI_BASE 	0x40010400
#define NVIC_BASE	0xE000E000
#define AFIO_BASE	0x40010000

#define RCC_APB2ENR 	*(volatile uint32_t*)(RCC_BASE + 0x18)
#define GPIOA_CRH		*(volatile uint32_t*)(PORTA_BASE + 0x04)
#define GPIOA_ODR		*(volatile uint32_t*)(PORTA_BASE + 0x0c)
#define GPIOA_CRL		*(volatile uint32_t*)(PORTA_BASE + 0x00)
#define EXTI_IMR		*(volatile uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_PR			*(volatile uint32_t*)(EXTI_BASE + 0x14)
#define EXTI_RTSR		*(volatile uint32_t*)(EXTI_BASE + 0x08)
#define NVIC_PEN		*(volatile uint32_t*)(0xE000E100)
#define AFIO_EXTICR1	*(volatile uint32_t*)(AFIO_BASE +0x08)


void clock_init(){

	RCC_APB2ENR |= 1<<0; //clk for AFIO
	RCC_APB2ENR |= 1<<2; //clk for gpio A

}

void gpio_init(){
	//setting pin13 as output
	GPIOA_CRH   &= 0xFF0FFFFF;
	GPIOA_CRH   |= 0x00200000;
	//setting pin0 as floating input
	GPIOA_CRL |= 0b01 <<2;

}

int main(void)
{
	clock_init();
	gpio_init();
	EXTI_IMR |= 1<<0; // exti unmasked for first pin
	EXTI_RTSR |= 1<<0; //exti rising edge enabled
	NVIC_PEN |= 1<<6; //nvic ext0 enabled for first pin
	AFIO_EXTICR1 |= 0b0000<<0;


	while(1){
	}
	return 0;
}
void EXTI0_IRQHandler(void){
	//toggling gpioA pin0
	GPIOA_ODR ^= 1<<13;

	//clear pending register
	EXTI_PR |= 1<<0;
}
